name: macos

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3
      - name: Deps
        run: git submodule init && git submodule update
      - name: Build
        run: cargo build --all --all-targets --verbose
      - name: Run tests
        run: cargo test --all --all-targets --verbose
