name: macos

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build:
    # https://github.com/actions/runner-images
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3
      - name: clone and make redis
        run: |
          git clone https://github.com/redis/redis
          cd redis
          git checkout 7.0
          make REDIS_CFLAGS='-Werror' BUILD_TLS=yes && make install
          which redis-server && redis-server --version

      - name: deps
        run: git submodule update --init --recursive

      - name: rust-nightly
        run: |
          rustc -V
          rustup install nightly
          rustup default nightly
          rustc -V
      - name: build
        run: |
          cargo build --workspace --verbose \
            --exclude redisxann-faiss

      - name: test
        run: |
          cargo test --tests --workspace --verbose \
            --exclude redisxann-faiss \
            --exclude usearch
