name: Rust

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Deps
        run: git submodule update --init --recursive
      - name: Build
        run: |
          cargo build --workspace --verbose \
            --exclude redisxann-faiss
      - name: Run tests
        run: |
          cargo test --tests --workspace --all-targets --verbose \
            --exclude redisxann-faiss
