name: Rust

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  test-ubuntu-with-redis-7:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: clone and make redis
        run: |
          sudo apt-get install git
          git clone https://github.com/redis/redis
          cd redis
          git checkout 7.0
          make REDIS_CFLAGS='-Werror' BUILD_TLS=yes && make install
          which redis-server && redis-server

      - name: build redisxann modules
        run: |
          git submodule update --init --recursive
          cargo build --workspace --verbose \
            --exclude redisxann-faiss

      - name: test redisxann modules
        run: |
          cargo test --tests --workspace --verbose \
            --exclude redisxann-faiss
